chemin=open("chemin.txt","w")
contenuChemin=chemin.read()
print(contenuChemin)
# chemin.write("Salut")
# chemin.close()
# chemin2=open("WowArmory.lua","r+")
# contenuChemin2=chemin2.read()
# print(contenuChemin2)